name: Deploy API (Node + Apache)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install deps
        run: npm ci

      - name: Build (optional)
        run: npm run build --if-present

      - name: Rsync to server
        uses: burnett01/rsync-deployments@6.0
        with:
          switches: -avz --delete --exclude ".git" --exclude ".github" --exclude "node_modules"
          path: ./
          remote_path: /var/www/api/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Install server deps & restart service
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/backend
            npm ci || npm install
            sudo systemctl restart backend
